name: mayavi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=2.7
  - numpy
  - matplotlib
  - pandas
  - notebook
  - ipython
  - h5py
  - ipywidgets
  - mayavi
  - pip:
    - cloudpickle
