name: mayavi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=2.7
  - numpy
  - matplotlib
  - pandas
  - notebook
  - ipywidget
  - ipython
  - h5py
  - scikit-image<=0.20
  - scikit-learn<=0.20
  - mayavi
  - pip:
    - cloudpickle
