name: mayavi
channels:
- defaults
- conda-forge
dependencies:
- python=2.7
- mkl
- numpy
- scipy
- matplotlib
- pyqt
- vtk
- pandas
- scikit-learn
- scikit-image
- h5py
- pillow
- statsmodels
- jupyter
- sphinx
- joblib
- flake8
- spyder
- mayavi
- pip:
  - cloudpickle
